name: Battery Status Viewer (Local + Cloudflare Tunnel)
version: "1.0.1"
slug: local_battery_viewer_tunnel
description: Локальний адаптивний переглядач рівня заряду через Cloudflare Tunnel.
url: https://github.com/ardeus-ua/ha-battery-monitor-addon
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
stage: stable
panel_icon: mdi:battery-charging
map:
  - share: rw
ports:
  8099/tcp: 8099 # Flask-сервер
schema:
  log_level: list(debug|info|warning|error|fatal)?
  tunnel_domain: str # Домен, який буде використовувати тунель (наприклад, battery.mydomain.com)
secrets:
  - CLOUDFLARED_TOKEN # Токен авторизації Cloudflared
