name: Battery Status Viewer (Local + Cloudflare Tunnel)
version: "1.0.2"
slug: local_battery_viewer_tunnel
description: Локальний адаптивний переглядач рівня заряду трьох систем через Cloudflare Tunnel.
url: https://github.com/ardeus-ua/ha-battery-monitor
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application 
stage: stable
panel_icon: mdi:battery-charging
map:
  - share: rw # Дозволяє доступ до /share для creds.json
ports:
  8099/tcp: 8099 # Внутрішній порт Flask
host_network: true # Рекомендовано для Cloudflare Tunnel
schema:
  tunnel_domain: str # Домен, який буде використовувати тунель (наприклад, battery.mydomain.com)
  log_level: list(debug|info|warning|error|fatal)?
secrets:
  - CLOUDFLARED_TUNNEL_ID # ID вашого тунелю

# Аргументи збірки Docker для автоматичного визначення архітектури cloudflared
build_args:
  ARCH: "{{ arch }}"
